#!/usr/bin/env python3
""" Factor numbers """
from sys import argv
from math import sqrt


def factor_number(n):
    """Factors a single number and prints the result."""
    for i in range(1, int(sqrt(n)) + 1):
        if n % i == 0:
            print(f"{n}={i}*{n // i}")  # Multiply factors by 2
            break

def fac_list(ls):
    """factor each
    num in ls
    """
    for i in ls:
        find_and_times(i)


if len(argv) == 2:
    fac_list(open_read_file(argv[1]))
