#!/usr/bin/env python3
""" Factor numbers """
from sys import argv
from math import sqrt


def factor_number(n):
    """Factors a single number and prints the result."""
    for i in range(1, int(sqrt(n)) + 1):
        if n % i == 0:
            print(f"{n}={i}*{n // i}")  # Multiply factors by 2
            break

def main():
    """Reads numbers from a list and factors each one."""
    if len(sys.argv) == 2:
        with open(sys.argv[1], "r") as file:
            numbers = [int(line) for line in file]
        for number in numbers:
            factor_number(number)

if __name__ == "__main__":
    main()
